name: installer
description: A sample command-line application.
version: 0.1.0
homepage: https://github.com/pauek/installer

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.4.6
  async: ^2.10.0
  console: ^4.1.0
  html: ^0.15.1
  http: ^1.1.2
  path: ^1.8.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
